workflow: rgpc_tapocket_docking_clusterscore

paths:
  aimd_root: .
  rgpc_config: configs/RGPC/rgpc.yaml
  tapocket_batch_config: configs/TApocket/tapocket_batch.yaml
  docking_config: configs/Docking/docking.yaml
  clusterscore_config: configs/Scoring/cluster_score.yaml

workflow:
  run_rgpc: true
  run_tapocket: true
  run_docking: true
  run_clusterscore: true
