workflow_name: RGPC_to_TApocket

paths:
  aimd_root: .
  rgpc_config: configs/RGPC/rgpc.yaml
  tapocket_batch_config: configs/TApocket/tapocket_batch.yaml

workflow:
  run_rgpc: true
  run_tapocket: true
